/**
 * @fileoverview Controls all JS for the site.
 */

const SUBHEAD_SELECTOR = '.js-subhead';

export default class Core {
  subheadElem: HTMLElement;

  constructor() {
    this.subheadElem = document.querySelector(SUBHEAD_SELECTOR) as HTMLElement;
  }

  initialize(): void {
    this.subheadElem.innerHTML = 'this is generated by JS';
  }

}
